### ISSUE TITLE
github.io にもコーポレートサイト側で行った修正を取り込む

### ISSUE THREAD

**Issue by corink** [heartrails/heartrails.github.io#17]
- [x] ヘッダー
- [x] 各マージン

**Comment by corink** [comment]
@joraku 
~~github.io ページにも日英切り替えは必要でしょうか？~~

必要そうなのでそのようにします 🙆

**Comment by ramu** [comment]
@corink https://github.com/heartrails/heartrails.github.io/pull/18 こちらの対応( レビュー依頼中 )で一部取り込んじゃってる気がします。スタイル等気になる所あったら修正していただけると助かります

**Comment by corink** [comment]
済みなので閉じます。
