### ISSUE TITLE
jQuery version up

### ISSUE THREAD

**Issue by joraku** [heartrails/heartrails.github.io#26]

**Comment by kuboon** [comment]
PR 作るつもりで直接 push してしまった 
https://github.com/heartrails/heartrails.github.io/commit/b1a8a5ff03cb1f00b02a4e6b366bb3f2b6671963

**Comment by joraku** [comment]
@tgym 動作、問題なさそうですかね？

**Comment by tgym** [comment]
ざっと見て、以前の状態を覚えていませんが、特に挙動のおかしいところや表示の崩れは確認できず、問題ありません。
JS の直接の挙動は "scroll to top" ですが、こちらも正常動作です。
